#%RAML 1.0 NamedExample
post-salesforce-sapi-response: |
  {
    "orders": [
      {
        "id": "80109000006sBFEAA2",
        "number": "000000106",
        "products": [
          {
            "code": "keyboard", "quantity": 1
            },
          {
            "code": "mouse", "quantity": 3
          }
        ]
    },
     {
        "id": "80109000006sBFKKL1",
        "number": "000000105",
        "products": [
          {
            "code": "keyboard", "quantity": 6
            },
          {
            "code": "mouse", "quantity": 1
          }
        ]
      }
    ]
  }