#%RAML 1.0
title: salesforce-sapi

description: API for salesforce connection. 

mediaType:
  - application/json

protocols:
  - HTTPS

types:
  order: !include /exchange_modules/9bc3ba95-5f0d-4f01-8718-68464a7c5df0/order/1.0.2/order.raml
  product: !include /exchange_modules/9bc3ba95-5f0d-4f01-8718-68464a7c5df0/product/1.0.1/product.raml
  products:
    properties:
      product?:
        type: array
  orders:
    properties:
      order?:
        type: array

  error:
    type: object
    properties:
      message?:
        description: Error message
      details?:
        description: Detailed error message
    

uses:
  common: /exchange_modules/9bc3ba95-5f0d-4f01-8718-68464a7c5df0/common/1.0.0/common.raml

traits:
  client-id-required:
    headers:
      client_id:
        type: string
      client_secret:
        type: string

/order/products:
  post:
    is:
      - client-id-required
      - common.client-error:
          errorType: error
      - common.server-error:
          errorType: error
    description: Process given labels of products and return correct orderId from salesforce 
    displayName: Process productlabels
    body: 
      type: products
      examples: !include examples/post-salesforce-sapi-request.raml
    responses:
      200:
        body:
          type: orders
          examples: !include examples/post-salesforce-sapi-response.raml